"""expert knowledge table

The reference links that teach an expert. Somebody pastes a URL -- a catalogue
raisonné, a Levi's dating chart, a Fenton glass mark reference -- writes a line
about what it is for, and the expert reads it on every draft it applies to,
with no deploy.

`note` and `distillate` are two columns rather than one string, and that is the
security design rather than a schema preference: the note is the OWNER
speaking and is an instruction, the distillate was written from somebody
else's web page and is evidence that must be fenced. A single field holding
both could not be fenced differently.

`scope` is the other half: "global" reaches every draft and only a superadmin
writes one; "account" is one seller's and is filtered by account_id on every
read.

Autogenerated, unedited apart from this note: the agree-test compares the
migrations against the models on every run, so hand-tuning here is how the two
drift apart.

Revision ID: 0586887c43a2
Revises: 7b41c0d9e2a8
Create Date: 2026-09-13 03:23:53.925963
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0586887c43a2'
down_revision = '7b41c0d9e2a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_knowledge',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('expert', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=False),
    sa.Column('distillate', sa.String(length=8000), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('added_by', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_error', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_knowledge_account_id'), 'expert_knowledge', ['account_id'], unique=False)
    op.create_index(op.f('ix_expert_knowledge_expert'), 'expert_knowledge', ['expert'], unique=False)
    op.create_index('ix_expert_knowledge_lookup', 'expert_knowledge', ['expert', 'enabled', 'scope', 'account_id'], unique=False)
    op.create_index(op.f('ix_expert_knowledge_url_hash'), 'expert_knowledge', ['url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expert_knowledge_url_hash'), table_name='expert_knowledge')
    op.drop_index('ix_expert_knowledge_lookup', table_name='expert_knowledge')
    op.drop_index(op.f('ix_expert_knowledge_expert'), table_name='expert_knowledge')
    op.drop_index(op.f('ix_expert_knowledge_account_id'), table_name='expert_knowledge')
    op.drop_table('expert_knowledge')
    # ### end Alembic commands ###
