"""shipping labels table

One row per label a seller bought (or set out to buy) through their own
EasyPost account: written as "buying" BEFORE the purchase and flipped to
"bought" after, so a lost answer from EasyPost leaves a row that says "we may
have paid for this" and the next open of the order settles it instead of
asking the seller to go and look. Also the local record that scopes a
shipment id to its owner -- a label carries the buyer's name and address.

Autogenerated, unedited apart from this note: the agree-test compares the
migrations against the models on every run, so hand-tuning here is how the two
drift apart.

Revision ID: 22e5017c418a
Revises: 34ff73ca6a10
Create Date: 2026-09-09 06:04:53.863853
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '22e5017c418a'
down_revision = '34ff73ca6a10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_labels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('listing_record_id', sa.String(length=64), nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=False),
    sa.Column('rate_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tracking_number', sa.String(length=64), nullable=False),
    sa.Column('carrier', sa.String(length=32), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('cost', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('label_url', sa.String(length=1024), nullable=False),
    sa.Column('tracker_url', sa.String(length=1024), nullable=False),
    sa.Column('ebay_marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ebay_error', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_labels_order_id'), 'shipping_labels', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipping_labels_shipment_id'), 'shipping_labels', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipping_labels_user_id'), 'shipping_labels', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipping_labels_user_id'), table_name='shipping_labels')
    op.drop_index(op.f('ix_shipping_labels_shipment_id'), table_name='shipping_labels')
    op.drop_index(op.f('ix_shipping_labels_order_id'), table_name='shipping_labels')
    op.drop_table('shipping_labels')
    # ### end Alembic commands ###
