"""error events table

The queryable half of the app's first telemetry. Before this there was none:
stdout, Fly's bounded retention window, and a human running a workflow by hand
to read it. `error_events` holds one row per DISTINCT failure — the unique
constraint on `fingerprint` is the deduplication, so a bug hit ten thousand
times is one row saying ten thousand, and the table is bounded by how many
things are broken rather than by traffic.

Autogenerated, unedited apart from this note: the agree-test compares the
migrations against the models on every run, so hand-tuning here is how the two
drift apart.

Revision ID: 34ff73ca6a10
Revises: f3a9c1d24e07
Create Date: 2026-09-01 16:30:19.743590
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '34ff73ca6a10'
down_revision = 'f3a9c1d24e07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('error_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('exc_type', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('traceback', sa.String(length=8000), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('build', sa.String(length=40), nullable=False),
    sa.Column('module', sa.String(length=120), nullable=False),
    sa.Column('func', sa.String(length=120), nullable=False),
    sa.Column('lineno', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fix_pr', sa.String(length=200), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index('ix_error_events_last_seen', 'error_events', ['last_seen', 'id'], unique=False)
    op.create_index(op.f('ix_error_events_severity'), 'error_events', ['severity'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_error_events_severity'), table_name='error_events')
    op.drop_index('ix_error_events_last_seen', table_name='error_events')
    op.drop_table('error_events')
