"""initial schema

Revision ID: adcd7b70f0b3
Revises: 
Create Date: 2026-08-30 11:41:22.681390
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'adcd7b70f0b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_accounts',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.String(length=4096), nullable=False),
    sa.Column('ebay_user_id', sa.String(length=64), nullable=False),
    sa.Column('ebay_username', sa.String(length=128), nullable=False),
    sa.Column('ebay_email', sa.String(length=255), nullable=False),
    sa.Column('fulfillment_policy_id', sa.String(length=64), nullable=False),
    sa.Column('payment_policy_id', sa.String(length=64), nullable=False),
    sa.Column('return_policy_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_location_key', sa.String(length=64), nullable=False),
    sa.Column('ship_from_postal', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_ebay_accounts_ebay_user_id'), 'ebay_accounts', ['ebay_user_id'], unique=False)
    op.create_table('ebay_deletion_notices',
    sa.Column('notification_id', sa.String(length=128), nullable=False),
    sa.Column('ebay_user_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_ebay_deletion_notices_ebay_user_id'), 'ebay_deletion_notices', ['ebay_user_id'], unique=False)
    op.create_index(op.f('ix_ebay_deletion_notices_state'), 'ebay_deletion_notices', ['state'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_user_id'), 'listings', ['user_id'], unique=False)
    op.create_table('marketplace_accounts',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('marketplace', sa.String(length=32), nullable=False),
    sa.Column('refresh_token', sa.String(length=8192), nullable=False),
    sa.Column('external_username', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'marketplace')
    )
    op.create_table('media_purges',
    sa.Column('listing_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_media_purges_user_id'), 'media_purges', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=512), nullable=False),
    sa.Column('listing_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('token_accounts',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('purchased', sa.Integer(), nullable=False),
    sa.Column('free_used', sa.Integer(), nullable=False),
    sa.Column('free_period', sa.String(length=7), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('token_ledger',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('feature', sa.String(length=48), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('free_part', sa.Integer(), nullable=False),
    sa.Column('paid_part', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('ref', sa.String(length=128), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    op.create_index(op.f('ix_token_ledger_user_id'), 'token_ledger', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('sessions_valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sweep_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prefs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_ledger_user_id'), table_name='token_ledger')
    op.drop_table('token_ledger')
    op.drop_table('token_accounts')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_media_purges_user_id'), table_name='media_purges')
    op.drop_table('media_purges')
    op.drop_table('marketplace_accounts')
    op.drop_index(op.f('ix_listings_user_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_ebay_deletion_notices_state'), table_name='ebay_deletion_notices')
    op.drop_index(op.f('ix_ebay_deletion_notices_ebay_user_id'), table_name='ebay_deletion_notices')
    op.drop_table('ebay_deletion_notices')
    op.drop_index(op.f('ix_ebay_accounts_ebay_user_id'), table_name='ebay_accounts')
    op.drop_table('ebay_accounts')
    # ### end Alembic commands ###
