"""Alembic environment, pointed at the app's own models and URL.

Two things are deliberate here.

`target_metadata` is `db.Base.metadata` — the same object `create_all` uses —
so `--autogenerate` compares against exactly what the running app expects, and
a migration that drifts from the models shows up as a diff rather than as a
Postgres error on somebody's deploy.

The URL comes from `backend.config`, not from alembic.ini. The app already
knows how to normalize it (Neon hands out `postgres://`, SQLAlchemy 2 wants
`postgresql+psycopg2://`), and a URL written into a tracked ini file is both a
second source of truth and a credential in the repository.
"""
from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

from backend import config, db

if context.config.config_file_name is not None:
    fileConfig(context.config.config_file_name)

target_metadata = db.Base.metadata


def _url() -> str:
    url = context.get_x_argument(as_dictionary=True).get("url")
    return db._normalize_url(url or config.DATABASE_URL)


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it — `alembic upgrade head --sql`.

    Worth having: it is how an operator reviews what is about to run against a
    production database before letting it.
    """
    context.configure(url=_url(), target_metadata=target_metadata,
                      literal_binds=True, compare_type=True,
                      dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(_url(), poolclass=pool.NullPool)
    with connectable.connect() as connection:
        # No render_as_batch. It only changes how SQLite handles ALTER and
        # DROP COLUMN, which production (Postgres) never needs and which
        # would put batch blocks around plain CREATE INDEX in every
        # autogenerated migration. A future migration that has to ALTER a
        # column AND run against SQLite should wrap that one operation in
        # op.batch_alter_table itself, where the reason is visible.
        context.configure(connection=connection,
                          target_metadata=target_metadata,
                          compare_type=True)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
